version: '3.8'
services:
  db:
    image: postgres:17
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: pokemon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db